### ISSUE TITLE
font family

### ISSUE THREAD

**Issue by lukaszwos** [4GeeksAcademy/Instagram-feed-#2]
Set font family on body 

https://github.com/4GeeksAcademy/Instagram-feed-/blob/d5ffc74d249aea048a130534779d83a9b806d591/style.css#L5

**Comment by victorconceicao88** [comment]
Hi lukas i did i put Arial

**Comment by lukaszwos** [comment]
put this: 
` font-family: Arial, Helvetica, sans-serif;`
on body not on:
`#font-family`

**Comment by victorconceicao88** [comment]
ok perfect thanks for the feedback Lukas
